### ISSUE TITLE
Adding ScreenShot for README

### ISSUE THREAD

**Issue by gnekt** [gnekt/A-Python-TravelingSalesmanProblem-Solver#2]
![Schermata da 2021-07-21 19-46-54](https://user-images.githubusercontent.com/39567665/126536758-17fb0d9e-0be0-4387-9351-c1f487b0ac88.png)

**Comment by christiandimaio** [comment]
![Schermata da 2021-07-21 19-59-36](https://user-images.githubusercontent.com/39567665/126537290-ae761ff0-1fef-4fda-a1d0-aec91f16707f.png)
